#!/usr/bin/env node
import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { parseArgs } from "node:util";
import { loadConfig } from "./config.js";
import { renderEmbedText, type DiscordMessage } from "./discord/embed.js";
import { checkBotToken } from "./discord/post.js";
import { createLogger } from "./log.js";
import { runCycle, runSingleItem } from "./pipeline.js";

const log = createLogger("run");

/** Writes the rendered embed plus the exact payload, so an artifact is reviewable and replayable. */
async function writeMessageFile(
  path: string,
  sourceUrl: string,
  message: DiscordMessage,
  analyzer: string,
  channelId: string | undefined,
): Promise<void> {
  const channel = channelId ?? "$DISCORD_CHANNEL_ID";
  const [embed] = message.embeds;
  const contents = `# Discord embed: ${embed?.title ?? "(no embed)"}

Generated by \`npm run run -- --url ${sourceUrl}\` on ${new Date().toISOString()}.
Analyzer: ${analyzer}. Target channel: \`${channel}\`.

## As it renders in Discord

${renderEmbedText(message)}

## Exact POST /channels/${channel}/messages payload

\`\`\`json
${JSON.stringify(message, null, 2)}
\`\`\`
`;

  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, contents, "utf8");
}

async function main(): Promise<void> {
  const { values } = parseArgs({
    options: {
      url: { type: "string" },
      out: { type: "string" },
      "check-discord": { type: "boolean" },
    },
    allowPositionals: false,
  });

  const config = loadConfig();
  const startedAt = Date.now();

  if (values["check-discord"]) {
    if (!config.discordBotToken) {
      log.error("DISCORD_BOT_TOKEN is not set – there is no bot token to check");
      process.exitCode = 1;
      return;
    }
    const check = await checkBotToken(
      config.discordBotToken,
      config.discordChannelId,
      config.httpTimeoutMs,
    );
    if (check.ok) {
      log.info(`Discord bot: ${check.detail}`);
      return;
    }
    log.error(`Discord bot: ${check.detail}`);
    process.exitCode = 1;
    return;
  }

  const analyzerLabel = config.cursorApiKey
    ? `${config.cursorModel} via cursor ${config.cursorRuntime}`
    : "labeled restatement fallback";
  log.info(
    `starting run (dryRun=${config.dryRun}, database=${config.databaseUrl ? "postgres" : "memory"}, analyzer=${analyzerLabel})`,
  );

  if (values.url) {
    log.info(`single-item mode: ${values.url}`);
    const message = await runSingleItem(config, values.url);
    if (values.out) {
      await writeMessageFile(
        values.out,
        values.url,
        message,
        analyzerLabel,
        config.discordChannelId,
      );
      log.info(`wrote ${values.out}`);
    }
    log.info(`done in ${((Date.now() - startedAt) / 1000).toFixed(1)}s`);
    return;
  }

  const summary = await runCycle(config);
  const seconds = ((Date.now() - startedAt) / 1000).toFixed(1);

  const retried = summary.retried > 0 ? `, ${summary.retried} retried` : "";
  log.info(
    `done in ${seconds}s – ${summary.candidates} candidates, ${summary.newItems} new (${summary.seeded} seeded), ${summary.analyzed} analyzed${retried}, ${summary.issuesOpened} issues opened, ${summary.posted} posted`,
  );
  for (const note of summary.notes) log.info(`note: ${note}`);
}

main().catch((error: unknown) => {
  log.error("run failed", error instanceof Error ? (error.stack ?? error.message) : error);
  process.exitCode = 1;
});
